# SITE CONFIGURATION
encoding: UTF-8
title: John de Lara # your site title
author: johndelara1 # You :P
description: > # Meta description of Homepage
  Neste portfólio você poderá acompanhar meus projetos, análises e estudos relacionado à Ciência de Dados,
    aplicação de Machine Learning, entre outros.
baseurl: "/portfolioweb" # the subpath of your site, e.g. /blog
url: "https://johndelara1.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: John de Lara
  links:
    #- https://twitter.com/BenBalter
    #- https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/johndelara1
    #- https://plus.google.com/+BenBalter
    - https://github.com/johndelara1
    #- https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Início', link: '/'}
  - {name: 'Sobre', link: '/sobre'}
  - {name: 'Contato', link: '/contato'}

tagline: >
  Aqui você encontrará meus projetos, análises e estudos relacionado à Ciência de Dados, aplicação de Machine Learning, entre outros.

hero_img: posts/trajetoria_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

hero_img1: posts/sleek_lg.jpg

email: johndelara1@gmail.com # email for form submission

twitter_username: johndelara01 # replace with your_twitter_username or comment to remove link from footer
github_username:  johndelara1 # replace with your_github_username or comment to remove link from footer
instagram_username: johndelara1 # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: john # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-5Z9JZD7 # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

theme: jekyll-theme-slate